vertigodjango/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

from vertigo import views
from vertigo.models import Equipment

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('import/', views.import_page, name='import'),
    path('logout/', views.logout_page, name='logout'),
    path('admin/', admin.site.urls),
    path('export/', views.export_pdf, name="export"),
    path('<slug:url_type>/accord/', views.agreement_page, name='agreement_url'),

    path('<slug:url_type>/', views.list_page, name='list_url'),
    path('<slug:url_type>/emprunt/id-<int:item_id>', views.borrowing_page, name='borrowing_url'),

    path('', views.list_page, {'url_type': Equipment.ROPE.url}, name='default'),  # Default page
]

vertigo/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.dispatch import receiver
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify

import phonenumbers
from phonenumber_field.modelfields import PhoneNumberField


@receiver(post_save, sender=User)
def create_or_update_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


# Hack to display user full name in forms select field
def override_user_str(self):
    return "{} {}".format(self.first_name, self.last_name)


User.add_to_class('__str__', override_user_str)


class Profile(models.Model):
    """
        Profil data liked to User model
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")

    license = models.CharField('licence', unique=True, max_length=12)  # 3401 2017 9039 blank=True
    phone = PhoneNumberField('téléphone', null=True, blank=True)
    # birth_date = models.DateField('date de naissance', null=True, blank=True)
    medical_date = models.DateField('date du certificat', null=True, blank=True)
    medical_file = models.FileField('certificat médical', upload_to='medical_certs/%Y/', null=True, blank=True)
    agreement = models.BooleanField('accord de responsabilité', default=False)
    forbidden = models.BooleanField('interdit d\'emprunt', default=False)

    def formatted_phone(self):
        if self.phone:
            return phonenumbers.format_number(self.phone, phonenumbers.PhoneNumberFormat.NATIONAL)
    formatted_phone.short_description = 'téléphone'


class EquipmentType:
    """
        Simple class to handle Equipment type conjugation and reference
    """
    def __init__(self, singular, plural, gender):
        self.singular = singular
        self.plural = plural
        self.url = slugify(plural)
        self.gender = gender


class Equipment(models.Model):
    """
        Model data for all equipment gear
    """

    # Do not modify after database is initialized, only append to the end
    # TODO: add localization if needed
    ROPE = EquipmentType('corde', 'cordes', 'la')
    RAPPEL = EquipmentType('rappel', 'rappels', 'le')
    QUICKDRAW = EquipmentType('dégaines', 'dégaines', 'les')
    LANYARD = EquipmentType('longe', 'longes', 'la')
    HARNESS = EquipmentType('baudrier', 'baudriers', 'le')
    HELMET = EquipmentType('casque', 'casques', 'le')
    CRASHPAD = EquipmentType('crashpad', 'crashpads', 'le')

    TYPE_LIST = [ROPE, RAPPEL, QUICKDRAW, LANYARD, HARNESS, HELMET, CRASHPAD]  # Must be exact number as above

    # TYPES = {}
    # for item in TYPE_LIST:
    #     TYPES[item.ref] = {'singular': item.singular, 'plural': item.plural}

    TYPE_CHOICE = [(equipment.url, equipment.singular) for equipment in TYPE_LIST]

    YEAR_CHOICE = []
    now = timezone.now().year
    for n in range(now, now - 11, -1):
        YEAR_CHOICE.append((n, n))

    ref = models.IntegerField(
        'numéro', help_text='le numéro donné par l\'association', blank=True, null=True, db_index=True)
    type = models.CharField('type', max_length=20, choices=TYPE_CHOICE, default=ROPE.url)
    status = models.BooleanField('en usage', help_text='décocher si réformé', default=True, db_index=True)

    brand = models.CharField('marque', max_length=50, blank=True)
    model = models.CharField('model', max_length=50, blank=True)

    serial_number = models.CharField('numéro de série', max_length=50, blank=True)
    year_of_manufacture = models.IntegerField('date de fabrication', choices=YEAR_CHOICE, blank=True, null=True)
    date_of_purchase = models.DateField('date d\'achat', blank=True, null=True)
    date_of_first_use = models.DateField('date de première utilisation', blank=True, null=True)

    caution = models.CharField(
        'avertissement', help_text='un court text accolé au nom du matériel', max_length=50, blank=True)
    comment = models.TextField('commentaire', max_length=3, blank=True)

    class Meta:
        verbose_name = 'équipement'
        verbose_name_plural = 'équipements'
        ordering = ('-status', 'type', 'ref')

    def __str__(self):
        message = " ({})".format(self.caution) if self.caution else ''
        return '{type} n°{ref}{caution}'.format(type=self.get_type_display(), ref=self.ref, caution=message)

    def clean(self):

        now = timezone.now().date()

        if self.year_of_manufacture:
            if self.year_of_manufacture > now.year:
                raise ValidationError(
                    {'year_of_manufacture': 'la date de fabrication doit être antérieur à la date du jour'})

        if self.date_of_purchase:
            if self.date_of_purchase > now:
                raise ValidationError(
                    {'date_of_purchase': 'la date d\'achat doit être antérieur à la date du jour'})

        if self.date_of_first_use:
            if self.date_of_first_use > now:
                raise ValidationError(
                    {'date_of_first_use': 'la date de premier usage doit être antérieur à la date du jour'})

        if self.date_of_purchase and self.year_of_manufacture:
            if self.date_of_purchase.year < self.year_of_manufacture:
                raise ValidationError(
                    {'date_of_purchase': 'la date d\'achat doit être antérieur à la date de fabrication'})

        if self.date_of_purchase and self.date_of_first_use:
            if self.date_of_purchase > self.date_of_first_use:
                raise ValidationError(
                    {'date_of_first_use': 'la date de premier usage doit être postérieur à la date d\'achat'})

        # Don't allow creating an equipment when existing one with same ref and is in use
        if not self.pk:
            if Equipment.objects.filter(type=self.type, ref=self.ref, status=True).exists():
                raise ValidationError(
                    {'ref': 'un·e {} en cours d\'usage existe déjà avec ce numéro'.format(self.get_type_display())})


class Topo(models.Model):

    TOPO = EquipmentType('topo', 'topos', 'le')
    MAP = EquipmentType('carte', 'cartes', 'la')
    TYPE_LIST = [TOPO, MAP]

    TYPE_CHOICE = [(topo.url, topo.singular) for topo in TYPE_LIST]

    YEAR_CHOICE = []
    for n in range(timezone.now().year, timezone.now().year - 30, -1):
        YEAR_CHOICE.append((n, n))

    title = models.CharField('titre', max_length=70, blank=True, null=True)
    ref = models.CharField('référence', max_length=70, blank=True, null=True)
    type = models.CharField('type', max_length=10, choices=TYPE_CHOICE, default='climbing', blank=True, null=True)
    year_of_edition = models.IntegerField('année d\'édition', choices=YEAR_CHOICE, blank=True, null=True)
    date_of_purchase = models.DateField('date d\'achat', blank=True, null=True)
    cover = models.ImageField('couverture', upload_to='topos', blank=True, null=True)
    status = models.BooleanField('disponible', help_text='décocher si perdu ou retiré', default=True, db_index=True)

    def cover_html(self):
        return mark_safe('<img src="/static/media/{}" width="64" />'.format(self.cover))
    cover_html.short_description = 'Couverture'

    def __str__(self):
        return '{type} {title}'.format(type=self.get_type_display(), title=self.title)

    class Meta:
        verbose_name = 'topo'
        verbose_name_plural = 'topos'


class Borrowing(models.Model):
    """Borrowing model linking an Equipment to a User"""

    user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='par', blank=True, null=True)
    date = models.DateField('emprunté le', db_index=True)  # default=timezone.now

    class Meta:
        abstract = True

    @property
    def color(self):
        diff = timezone.now().date() - self.date
        d = int(diff.days)
        color = 'dark'
        if d < 2:
            color = 'success'
        elif d < 7:
            color = 'secondary'
        elif d < 14:
            color = 'warning'
        elif d < 21:
            color = 'danger'
        return color


class EquipmentBorrowing(Borrowing):
    """Borrowing relation between an Equipment and a User"""

    item = models.ForeignKey(Equipment, on_delete=models.PROTECT, verbose_name='équipement')

    class Meta:
        verbose_name = 'emprunt'
        verbose_name_plural = 'emprunts de matériel'
        ordering = ('-date', '-id')

    def __str__(self):
        return 'Emprunt {item} par {user}'.format(item=self.item, user=self.user.first_name)


class TopoBorrowing(Borrowing):
    """Borrowing model linking a Topo or Map to a User"""

    item = models.ForeignKey(Topo, on_delete=models.PROTECT, verbose_name='topo')

    class Meta:
        verbose_name = 'emprunt'
        verbose_name_plural = 'emprunts de topo'
        ordering = ('-date', '-id')

    def __str__(self):
        return 'Emprunt {item} par {user}'.format(item=self.item, user=self.user.first_name)

templates/agreement.html
{% extends 'base.html' %}

{% block page_title %}Accord de responsabilité{% endblock %}
{% block navbar_title %}Accord de responsabilité{% endblock %}

{% block container %}

    <div class="container px-3">

        <div class="card bg-light mt-3">

            <div class="card-body">
                <p class="card-text">En empruntant du matériel à l'association Vertigo, je m'engage à en prendre soin lors de son usage, à le stocker dans de bonnes conditions et à le ramener le jeudi suivant dans les mains du responsable matériel.</p>
                <p class="card-text">Tout manquement à ces principes pourra entraîner une suspension du droit à l'emprunt au sein de l'association et dans le cas d'une perte, au remboursement de toute ou partie du matériel en question.</p>

                <div class="row">
                    <div class="col">
                        <form action="{% url 'logout' %}">
                            <button class="btn btn-lg btn-light btn-block" type="submit">Je refuse</button>
                        </form>
                    </div>
                    <div class="col">
                        <form action="{% url 'agreement_url' url_type %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="agreement" value="true" />
                            <button class="btn btn-lg btn-danger btn-block" type="submit">J'accepte</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Site meta tags and more -->
    <meta name="description" content="Application web de gestion du matériel pour l'association d'escalade et canyoning Vertigo à Montpellier." />
    <meta name="author" content="Rémi de Chazelles">
    <!-- Chrome, Firefox OS and Opera -->
    <meta name="theme-color" content="#C93F3F">
    <!-- Windows Phone -->
    <meta name="msapplication-navbutton-color" content="#C93F3F">
    <!-- iOS Safari -->
    <meta name="apple-mobile-web-app-status-bar-style" content="#C93F3F">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <title>{% block page_title %}{% endblock %} | Vertigo</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

</head>

<body>

    <nav class="navbar navbar-expand-md navbar-dark red-vertigo fixed-top">
        <span class="navbar-brand">{% block navbar_title %}{% endblock %}</span>
        {% if user.is_authenticated and types %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Basculer la navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

            {% for type in types %}
                <li class="nav-item{% if type.url == current_type.url %} active{% endif %}">
                    <a class="nav-link" href="{% url 'list_url' type.url %}">{{ type.plural|title }}</a>
                </li>
            {% endfor %}

            </ul>

            <ul class="navbar-nav">
                <li class="nav-item active">
                    <span class="nav-link">{{ user.get_short_name }} (<a class="font-italic text-white" href="{% url 'logout' %}">déconnecter</a>)</span>
                </li>
            </ul>
        </div>
        {% endif %}
    </nav>

        {% block container %}{% endblock %}

    <!-- footer -->
    <div class="text-center">
    <img src="{% static '/img/logo.png' %}" class="mx-auto d-block top-margin" alt="Logo Vertigo" height="64">
        <p class="discret top-padding-sm"><small>VertigoDjango 0.1.0{% if perms.vertigo.add_equipment %} - <a href="{% url 'admin:index' %}">Administration</a></small>{% endif %}</p>
    </div>

    <!-- JS libs -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    {% block script %}{% endblock %}

</body>
</html>

templates/borrowing.html
{% extends 'base.html' %}

{% block page_title %}Emprunt {{ current_type.singular }} n°{{ equipment_ref }}{% endblock %}
{% block navbar_title %}{{ current_type.singular|capfirst }} n°{{ equipment_ref }}{% endblock %}

{% block container %}
    <div class="container px-3">
        <form class="mt-3" action="{% url 'borrowing_url' current_type.url equipment_id %}" method="post">

            {% csrf_token %}

            {% for field in form %}
                {{ field.non_field_errors }}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {{ field.errors }}
                </div>
            {% endfor %}

            <div class="row mt-4">
                <div class="col">
{#                    <a class="btn btn-lg btn-light btn-block" type="button" id="cancel" href="{% url 'list_url' current_type.url %}">Annuler</a>#}
                    <button class="btn btn-lg btn-light btn-block" type="submit" name="cancel" value="True">Annuler</button>
                </div>
                <div class="col">
                    <button class="btn btn-lg btn-outline-success btn-block" type="submit">Valider</button>
                </div>
            </div>

        </form>
    </div>

{% endblock %}

templates/import.html
{% extends 'base.html' %}

{% block page_title %}Import des adhérents{% endblock %}
{% block navbar_title %}Import des adhérents{% endblock %}

{% block container %}
    <div class="container px-3">

            {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible mx-3 my-3 text-left" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}

        <form class="mt-3" action="{% url 'import' %}" method="post" enctype="multipart/form-data">

            {% csrf_token %}

            {% for field in form %}
                {{ field.non_field_errors }}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {{ field.errors }}
                </div>
            {% endfor %}

            <div class="row mt-4">
{#                <div class="col">#}
{#                    <button class="btn btn-lg btn-light btn-block" type="submit" name="cancel" value="True">Annuler</button>#}
{#                </div>#}
                <div class="col">
                    <button class="btn btn-lg btn-outline-success btn-block" type="submit">Valider</button>
                </div>
            </div>

        </form>
    </div>

{% endblock %}

templates/list.html
{% extends 'base.html' %}

{% block page_title %}Liste des {{ current_type.plural }}{% endblock %}
{% block navbar_title %}Liste des {{ current_type.plural }}{% endblock %}

{% block container %}

    {% if data %}

    <div class="container">

        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible mx-3 my-3 text-left" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}

        <table class="table table-striped table-hover white-bg opaque ">
            <thead>
                <tr>
                    <th>n°</th>
                    <th>Responsable</th>
                    <th>Depuis&nbsp;le</th>
                </tr>
            </thead>
            <tbody>
            {% for row in data %}
                <tr class='clickable-row' data-url="{% url 'borrowing_url' current_type.url row.item_id %}">
                    <td><span class="badge badge-pill badge-{{ row.color }}">{{ row.item.ref }}</span></td>
                    <td>{{ row.user.get_full_name|default_if_none:"---" }}</td>

                    <td class="td-center">{{ row.date|date:"j N" }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <div class="text-center mt-4" >
            <form action="{% url 'export' %}">
                <button type="submit" class="btn btn-outline-success"><i class="fas fa-download mr-2"></i> Exporter la liste au format PDF</button>
            </form>
{#            <a href="{% url 'export' %}" type="button" class="btn btn-outline-success"><i class="fas fa-download mr-2"></i> Exporter la liste au format PDF</a>#}
        </div>
    </div>

    {% else %}

    <div class="container px-3">
        <div class="alert alert-primary mt-3" role="alert">Il n'y a pas encore d'emprunt enregistré...</div>
    </div>

    {% endif %}

{% endblock %}

{% block script %}
    <script>
        jQuery(document).ready(function($) {
            $('.clickable-row').click(function() {
                window.location = $(this).data('url');
            });
        });
    </script>
{% endblock %}

templates/list_topo.html
{% extends 'base.html' %}

{% block page_title %}Liste des {{ current_type.plural }}{% endblock %}
{% block navbar_title %}Liste des {{ current_type.plural }}{% endblock %}

{% block container %}

    {% if data %}

    <div class="container">

        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible mx-3 my-3 text-left" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}

        <table class="table table-striped table-hover white-bg opaque ">
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Responsable</th>
                    <th>Depuis&nbsp;le</th>
                </tr>
            </thead>
            <tbody>
            {% for row in data %}
                <tr class='clickable-row' data-url="{% url 'borrowing_url' current_type.url row.item_id %}">
                    <td>{{ row.item.title }}</td>
                    <td>{{ row.user.get_full_name|default_if_none:"---" }}</td>

                    <td class="td-center">{{ row.date|date:"j N" }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <div class="text-center mt-4" >
            <form action="{% url 'export' %}">
                <button type="submit" class="btn btn-outline-success"><i class="fas fa-download mr-2"></i> Exporter la liste au format PDF</button>
            </form>
{#            <a href="{% url 'export' %}" type="button" class="btn btn-outline-success"><i class="fas fa-download mr-2"></i> Exporter la liste au format PDF</a>#}
        </div>
    </div>

    {% else %}

    <div class="container px-3">
        <div class="alert alert-primary mt-3" role="alert">Il n'y a pas encore d'emprunt enregistré...</div>
    </div>

    {% endif %}

{% endblock %}

{% block script %}
    <script>
        jQuery(document).ready(function($) {
            $('.clickable-row').click(function() {
                window.location = $(this).data('url');
            });
        });
    </script>
{% endblock %}

templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="fr" class="height: 100%">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Site meta tags and more -->
    <meta name="description" content="Application web de gestion du matériel pour l'association d'escalade et canyoning Vertigo à Montpellier." />
    <meta name="author" content="Rémi de Chazelles">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <title>Gestion du matériel | Vertigo</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

</head>

<body class="form-body text-center">

    <form class="form-signin" method="POST" action="{% url 'login' %}">

        {% csrf_token %}

        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible mb-4 text-left" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}

        <img class="mx-auto d-block mb-4" src="{% static '/img/logo.png' %}" alt="Logo Vertigo" height="64">

        {% if form.errors %}
            <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <span class="font-weight-bold">Erreur :</span> identifiant ou mot de passe invalide...
            </div>
        {% endif %}

        <h1 class="h4 mb-2 font-weight-normal">Gestion du matériel</h1>
        <input type="hidden" name="next" value="{{ next }}" />
        <label for="id_username" class="sr-only">Identifiant</label>
        <input type="text" id="id_username" name="username" class="form-control" placeholder="Identifiant" required>
        <label for="id_password" class="sr-only">Mot de passe</label>
        <input type="password" id="id_password" name="password" class="form-control" placeholder="Mot de passe" required>
        <button class="btn btn-lg btn-danger btn-block mt-4 red-vertigo" type="submit">Connexion</button>
    </form>

    <!-- JS libs -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

</body>
</html>